### ISSUE TITLE
Packages missing for Wok in 17082016

### ISSUE THREAD

**Issue by MalleshKoti** [open-power-host-os/builds#27] opened 2016-08-23 10:19 UTC
--Problem Description--
Following packages are missing for Wok:
1. Wok
2. Kimchi
3. Ginger
4. Ginger-base

--uname output--
uname -a
Linux c158f2u07os.pok.stglabs.ibm.com 4.7.0-1.el7.centos.pkvm3_1_1.3100.0.ppc64le #1 SMP Wed Aug 17 13:38:15 CDT 2016 ppc64le ppc64le ppc64le GNU/Linux

We are blocked from testing because of these package missing.

**Comment by maurorodrigues** [comment] 2016-08-24 04:54
Duplicate of #8

**Closed by maurorodrigues** 2016-08-24 04:54 UTC
Labels: duplicate
