### ISSUE TITLE
HostOS release package

### ISSUE THREAD

**Issue by maurorodrigues** [open-power-host-os/builds#53] opened 2016-09-04 15:49 UTC
Pretty much like epel does, see the files epel packages:

```
[user@jaspion1 builds]$ rpm -qpl ~/epel-release-7-5.noarch.rpm 
/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
/etc/yum.repos.d/epel-testing.repo
/etc/yum.repos.d/epel.repo
/usr/lib/rpm/macros.d/macros.epel
/usr/lib/systemd/system-preset/90-epel.preset
/usr/share/doc/epel-release-7
/usr/share/doc/epel-release-7/GPL
```

**Comment by maurorodrigues** [comment] 2016-09-05 17:26
Epel Spec file http://pkgs.fedoraproject.org/cgit/rpms/epel-release.git/tree/epel-release.spec?id=9042f1e82b481b8e1ba8cac3e1de6ddf15b59e28

**Comment by olavphibm** [comment] 2016-09-08 15:02
.repo is enough for internal repositories. Update to use latest repository.

**Comment by olavphibm** [comment] 2016-09-30 18:35
Duplicate of #84

**Comment by maurorodrigues** [comment] 2016-10-04 13:24
@olavphibm sorry I wasn't clear at all when I created this hehe, this isn't about how to install the repository in a system, even though that's what it obviously does (which is kind of useless as you mentioned it could be done using the .repo pointing to the latest repo instead).

This is about a way to keep test team aware of which 'version' (or build) of hostOS they're testing when there is no update in the package versions (because there is no new commits). @sathnaga @rquander and I discussed several weeks ago and we agreed that we need to identify somehow which build they're testing, even when there is no change in order to avoid duplicate their work testing same software in 2 different builds (I think in the third weekly build for instance there was no package change, release_version was bumped even though it wasn't necessary and that duplicated their test effort).

We can extend this bug to cover #42, #43, #84 and #55 containing data like
/etc/sysconfig/hostos/some_special_script_that_closes_#84
/usr/share/doc/new_packages_list_from_issue_#55
/usr/share/doc/release_notes_generated_by_43

and so on, it would be something to distribute for our test team only as metadata.

What you guys think?

**Comment by rquander** [comment] 2016-10-04 14:31
@maurorodrigues my preference would be to abort the build completely if there are no changes involved. I don't see any reason to waste build, BVT, test, or post/upload time on a build with no changes from the last most recent.  If additional coding/configuration is necessary to enable build abort on no change then I'd rather change this Issue to track that or open a new issue for that and re-close this one.
@sathnaga thoughts?

**Comment by maurorodrigues** [comment] 2016-10-04 22:18
@rquander while I do agree with you on that, and it's very easy to do it, I also think there are people in the organization that expect weekly builds no matter what, somehow I feel like user's confidence on hostOS kind of rely on that. I skipped the build on the second week IIRC and got several questions about it.

Anyway let's discuss this and see what @rmatinata-ibm thinks about it. I'm totally fine skipping build when there is no changes in **all** packages.

**Comment by maurorodrigues** [comment] 2016-10-04 22:22
Regarding using this single RPM to close all the issues I mentioned @olavphibm already gave a good reason to not include it all together: The RPM containing HostOS setup (#84) is useful for users as well and the purpose here is to offer metadata to our test team, so they're different tasks.

**Comment by mopsfelder** [comment] 2016-10-07 00:54
If the purpose of this package is only to identify which HostOS release number user is running, I suggest we have a package, e.g. `openpower_hostos-release`, that only delivers `/etc/openpower_hostos-release` file containing the weekly build number or the released build number.

If we brush `openpower_host-release` package a little bit, we could make it depend on the exact versions of other packages delivered by HostOS, e.g. kernel, qemu, libvirt, SLOF, and so on.  Thus installing an specific version of `openpower_hostos-release` package would pull in specific versions of delivered packages that match the release package numbering.

**Comment by mfoliveira** [comment] 2017-02-07 23:56
> If we brush openpower_host-release package a little bit, we could make it depend on the exact versions of other packages delivered by HostOS, e.g. kernel, qemu, libvirt, SLOF, and so on. Thus installing an specific version of openpower_hostos-release package would pull in specific versions of delivered packages that match the release package numbering.

This would be more than welcome.
The current approach of copying/pasting/cat'ing lists of packages could be improved.

**Comment by olavphibm** [comment] 2017-03-31 18:47
We now have `open-power-host-os-release` and group metapackages, with their installation described at https://github.com/open-power-host-os/builds/blob/master/INSTALLING_PACKAGES.md#installation-using-yum-repository and their details describe at https://github.com/open-power-host-os/versions/blob/master/README.md#release-package.
They cover the identification of the current OpenPOWER Host OS release, installing groups of packages, making sure the installed packages match the current Host OS version and configuration of system-wide options (e.g. disabling SMT). They also configure publicly available repositories (CentOS and EPEL) though dependencies.

**Closed by olavphibm** 2017-03-31 18:47 UTC
Labels: ci, feature request, idea, package
